### PR TITLE
chore: updated dependencies

### PR DESCRIPTION
**Pull request by philsturgeon**
Dependabot was left to go wild for months so let's take a swing at bulk updates.

### CODE REVIEW

**Comment by P0lip** [comment]
@philsturgeon ah, some of deps may require code code changes, I'll try to see which PRs require so and update anything that's needed. Then, we can merge the PR, as in fact the PRs become a bit stale.

**Comment by philsturgeon** [comment]
Feel free to take this over. I was curious to see if our tests would vomit, and they did. we should also get the tests running on more than just node 8 because we use this on 10 and 12 a lot.

**Comment by P0lip** [comment]
> the tests running on more than just node 8 because we use this on 10 and 12 a lot.

HA! Believe me or not, but this was my thought too.
I guess we could have a similar setup to Spectral in terms of Node versions.
Thoughts?

**Comment by philsturgeon** [comment]
Yeah some copy pasta should do the trick. 🍝🍝

**Pull request merged**
